apiVersion: v1
kind: Namespace
metadata:
  name: moodsync-production
  labels:
    name: moodsync-production
    environment: production
    app: moodsync
  annotations:
    description: "MoodSync production environment namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: moodsync-resource-quota
  namespace: moodsync-production
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "50"
    configmaps: "50"
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: moodsync-limit-range
  namespace: moodsync-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim